exchanges:
  BINGX:
  - 0G/USDT
  - 0G/USDT:USDT
  - 1000000BABYDOGE/USDT:USDT
  - 1000000BOB/USDT:USDT
  - 1000000MOG/USDT:USDT
  - 10000SATS/USDT:USDT
  - 1000BONK/USDT:USDT
  - 1000CAT/USDT:USDT
  - 1000CHEEMS/USDT:USDT
  - 1000PEPE/USDT:USDT
  - 1INCH/USDT
  - 1INCH/USDT:USDT
  - 2Z/USDT
  - 2Z/USDT:USDT
  - 4/USDT
  - 4/USDT:USDT
  - 4EVER/USDT
  - 5IRE/USDT
  - 9BIT/USDT
  - A/USDT
  - A/USDT:USDT
  - A2Z/USDT
  - A2Z/USDT:USDT
  - AAPLON/USDT
  - AAPLX/USDT
  - AAVE/USDT
  - AAVE/USDT:USDT
  - AB/USDT
  - ABTON/USDT
  - ACE/USDT
  - ACE/USDT:USDT
  - ACH/USDT
  - ACH/USDT:USDT
  - ACM/USDT
  - ACNON/USDT
  - ACT/USDT
  - ACT/USDT:USDT
  - ACU/USDT
  - ACU/USDT:USDT
  - ACX/USDT
  - ACX/USDT:USDT
  - ADA/USDT
  - ADA/USDT:USDT
  - AERGO/USDT
  - AERGO/USDT:USDT
  - AERO/USDT
  - AERO/USDT:USDT
  - AEVO/USDT
  - AEVO/USDT:USDT
  - AGENC/USDT:USDT
  - AGI/USDT
  - AGLD/USDT:USDT
  - AGT/USDT
  - AGUSTO/USDT
  - AIA/USDT
  - AIA/USDT:USDT
  - AIC/USDT
  - AIN/USDT
  - AIN/USDT:USDT
  - AIO/USDT
  - AIOT/USDT:USDT
  - AIOZ/USDT
  - AITECH/USDT
  - AITO/USDT
  - AIXBT/USDT
  - AIXBT/USDT:USDT
  - AKE/USDT
  - AKE/USDT:USDT
  - AKT/USDT
  - AKT/USDT:USDT
  - ALCH/USDT
  - ALCX/USDT
  - ALEO/USDT
  - ALGO/USDT
  - ALGO/USDT:USDT
  - ALI/USDT
  - ALICE/USDT
  - ALICE/USDT:USDT
  - ALLO/USDT
  - ALLO/USDT:USDT
  - ALMANAK/USDT
  - ALPACA/USDT
  - ALPINE/USDT
  - ALPINE/USDT:USDT
  - ALT/USDT
  - ALT/USDT:USDT
  - ALU/USDT
  - AMP/USDT
  - AMZNON/USDT
  - ANDY/USDT
  - ANIME/USDT
  - ANIME/USDT:USDT
  - ANKR/USDT
  - ANKR/USDT:USDT
  - APE/USDT
  - APE/USDT:USDT
  - APEPE/USDT
  - APEX/USDT
  - APEX/USDT:USDT
  - API3/USDT
  BYBIT:
  - 0G/USDT
  - 0G/USDT:USDT
  - 1000000BABYDOGE/USDT:USDT
  - 1000000CHEEMS/USDT:USDT
  - 1000000MOG/USDT:USDT
  - 10000QUBIC/USDT:USDT
  - 10000SATS/USDT:USDT
  - 1000BONK/USDT:USDT
  - 1000BTT/USDT:USDT
  - 1000CAT/USDT:USDT
  - 1000FLOKI/USDT:USDT
  - 1000LUNC/USDT:USDT
  - 1000NEIROCTO/USDT:USDT
  - 1000PEPE/USDT:USDT
  - 1000RATS/USDT:USDT
  - 1000TAG/USDT:USDT
  - 1000TOSHI/USDT:USDT
  - 1000TURBO/USDT:USDT
  - 1000XEC/USDT:USDT
  - 1INCH/USDT
  - 1INCH/USDT:USDT
  - 2Z/USDT
  - 2Z/USDT:USDT
  - 4/USDT:USDT
  - A/USDT
  - A/USDT:USDT
  - A8/USDT
  - AAPLX/USDT
  - AAVE/USDT
  - AAVE/USDT:USDT
  - ACE/USDT:USDT
  - ACH/USDT
  - ACH/USDT:USDT
  - ACS/USDT
  - ACT/USDT:USDT
  - ACU/USDT:USDT
  - ACX/USDT:USDT
  - ADA/USDT
  - ADA/USDT:USDT
  - AEDZ/USDT
  - AERGO/USDT:USDT
  - AERO/USDT
  - AERO/USDT:USDT
  - AEVO/USDT
  - AEVO/USDT:USDT
  - AFC/USDT
  - AGI/USDT
  - AGI/USDT:USDT
  - AGLD/USDT
  - AGLD/USDT:USDT
  - AIO/USDT:USDT
  - AIOZ/USDT
  - AIOZ/USDT:USDT
  - AIXBT/USDT
  - AIXBT/USDT:USDT
  - AKE/USDT:USDT
  - AKT/USDT:USDT
  - ALCH/USDT
  - ALCH/USDT:USDT
  - ALGO/USDT
  - ALGO/USDT:USDT
  - ALICE/USDT:USDT
  - ALLO/USDT:USDT
  - ALMANAK/USDT
  - ALPINE/USDT:USDT
  - ALT/USDT
  - ALT/USDT:USDT
  - AMI/USDT
  - AMZNX/USDT
  - ANIME/USDT
  - ANIME/USDT:USDT
  - ANKR/USDT
  - ANKR/USDT:USDT
  - AO/USDT
  - APE/USDT
  - APE/USDT:USDT
  - APEX/USDT
  - APEX/USDT:USDT
  - API3/USDT:USDT
  - APR/USDT:USDT
  - APT/USDT
  - APT/USDT:USDT
  - AR/USDT
  - AR/USDT:USDT
  - ARB/USDT
  - ARB/USDT:USDT
  - ARC/USDT:USDT
  - ARIA/USDT:USDT
  - ARK/USDT:USDT
  - ARKM/USDT
  - ARKM/USDT:USDT
  - ARPA/USDT:USDT
  - ARTY/USDT
  - ASP/USDT:USDT
  - ASR/USDT:USDT
  - ASTER/USDT
  - ASTER/USDT:USDT
  - ASTR/USDT:USDT
  - AT/USDT:USDT
  - ATH/USDT
  KUCOIN:
  - 0G/USDT
  - 1INCH/USDT
  - 2Z/USDT
  - 9BIT/USDT
  - A/USDT
  - A2Z/USDT
  - A47/USDT
  - AAVE/USDT
  - ACH/USDT
  - ACQ/USDT
  - ACS/USDT
  - ACTSOL/USDT
  - ACU/USDT
  - ACX/USDT
  - ADA/USDT
  - ADI/USDT
  - ADX/USDT
  - AERGO/USDT
  - AERO/USDT
  - AEVO/USDT
  - AGI/USDT
  - AGLD/USDT
  - AGT/USDT
  - AI3/USDT
  - AIN/USDT
  - AIO/USDT
  - AIOZ/USDT
  - AITECH/USDT
  - AIXBT/USDT
  - AKE/USDT
  - AKT/USDT
  - ALEPH/USDT
  - ALEX/USDT
  - ALGO/USDT
  - ALICE/USDT
  - ALKIMI/USDT
  - ALLO/USDT
  - ALPINE/USDT
  - ALT/USDT
  - ALU/USDT
  - AMP/USDT
  - ANIME/USDT
  - ANKR/USDT
  - ANLOG/USDT
  - ANOME/USDT
  - ANYONE/USDT
  - APE/USDT
  - API3/USDT
  - APP/USDT
  - APR/USDT
  - APT/USDT
  - AR/USDT
  - ARB/USDT
  - ARCA/USDT
  - ARCSOL/USDT
  - ARIA/USDT
  - ARKM/USDT
  - ARPA/USDT
  - ART/USDT
  - ARTFI/USDT
  - ARTY/USDT
  - ASI/USDT
  - ASP/USDT
  - ASTER/USDT
  - ASTR/USDT
  - ATA/USDT
  - ATH/USDT
  - ATOM/USDT
  - AUCTION/USDT
  - AUDIO/USDT
  - AURORA/USDT
  - AVA/USDT
  - AVAAI/USDT
  - AVAIL/USDT
  - AVAX/USDT
  - AVNT/USDT
  - AWE/USDT
  - AXS/USDT
  - AZERO/USDT
  - AZTEC/USDT
  - B2/USDT
  - B3/USDT
  - BABY/USDT
  - BABYDOGE/USDT
  - BAL/USDT
  - BAN/USDT
  - BANANA/USDT
  - BAND/USDT
  - BARD/USDT
  - BAS/USDT
  - BAT/USDT
  - BAX/USDT
  - BB/USDT
  - BCH/USDT
  - BCUT/USDT
  - BDX/USDT
  - BELIEVE/USDT
  - BERA/USDT
  - BERT/USDT
  - BEST/USDT
  OKX:
  - 0G/USDT:USDT
  - 1INCH/USDT
  - 1INCH/USDT:USDT
  - 2Z/USDT
  - 2Z/USDT:USDT
  - A/USDT
  - A/USDT:USDT
  - AAPL/USDT:USDT
  - AAVE/USDT
  - AAVE/USDT:USDT
  - ACE/USDT
  - ACH/USDT
  - ACH/USDT:USDT
  - ACT/USDT
  - ACT/USDT:USDT
  - ACU/USDT:USDT
  - ADA/USDT
  - ADA/USDT:USDT
  - AERGO/USDT
  - AERO/USDT:USDT
  - AEVO/USDT
  - AEVO/USDT:USDT
  - AGLD/USDT
  - AGLD/USDT:USDT
  - AIXBT/USDT
  - AIXBT/USDT:USDT
  - ALGO/USDT
  - ALGO/USDT:USDT
  - ALLO/USDT
  - ALLO/USDT:USDT
  - AMD/USDT:USDT
  - AMZN/USDT:USDT
  - ANIME/USDT
  - ANIME/USDT:USDT
  - APE/USDT
  - APE/USDT:USDT
  - API3/USDT
  - API3/USDT:USDT
  - APR/USDT:USDT
  - APT/USDT
  - APT/USDT:USDT
  - AR/USDT
  - AR/USDT:USDT
  - ARB/USDT
  - ARB/USDT:USDT
  - ARG/USDT
  - ARKM/USDT
  - ARKM/USDT:USDT
  - ASP/USDT
  - ASTER/USDT
  - ASTER/USDT:USDT
  - ASTR/USDT
  - AT/USDT:USDT
  - ATH/USDT
  - ATH/USDT:USDT
  - ATOM/USDT
  - ATOM/USDT:USDT
  - AUCTION/USDT
  - AUCTION/USDT:USDT
  - AVAX/USDT
  - AVAX/USDT:USDT
  - AVNT/USDT
  - AVNT/USDT:USDT
  - AXS/USDT
  - AXS/USDT:USDT
  - AZTEC/USDT:USDT
  - BABY/USDT
  - BABY/USDT:USDT
  - BABYDOGE/USDT
  - BANANA/USDT
  - BAND/USDT
  - BAND/USDT:USDT
  - BARD/USDT
  - BARD/USDT:USDT
  - BAT/USDT
  - BAT/USDT:USDT
  - BCH/USDT
  - BCH/USDT:USDT
  - BEAT/USDT:USDT
  - BERA/USDT
  - BERA/USDT:USDT
  - BETH/USDT
  - BICO/USDT
  - BICO/USDT:USDT
  - BIGTIME/USDT
  - BIGTIME/USDT:USDT
  - BIO/USDT
  - BIO/USDT:USDT
  - BLUR/USDT
  - BLUR/USDT:USDT
  - BNB/USDT
  - BNB/USDT:USDT
  - BNT/USDT
  - BOME/USDT
  - BOME/USDT:USDT
  - BONK/USDT
  - BONK/USDT:USDT
  - BRETT/USDT:USDT
  - BREV/USDT
  - BREV/USDT:USDT
high_volatility_atr_pct: 0.5
min_volume: 100000
rsi_overbought: 70
rsi_oversold: 30
rsi_period: 14
telegram:
  bot_token: ''
  chat_id: ''
  enabled: false
timeframes:
- 1m
- 3m
- 5m
- 15m
- 1h
- 4h
